/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import dao.CategoriaProdutoDAO;
import dao.ProdutoDAO;
import entity.CategoriaProduto;
import entity.Produto;

/**
 *
 * @author fabio
 */
public class Test extends javax.swing.JInternalFrame {
    private static Test myInstance;
    
    public static Test getMyInstance(){
        if(myInstance == null)
            myInstance = new Test();
        return myInstance;
    }
    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInserir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluirProd = new javax.swing.JButton();
        btnExcCat = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Janela de Testes");

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluirProd.setText("Excluir Produto");
        btnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdActionPerformed(evt);
            }
        });

        btnExcCat.setText("Excluir Categoria");
        btnExcCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcCat)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluirProd)
                    .addComponent(btnExcCat))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        setBounds(0, 0, 426, 308);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        CategoriaProduto cat1 = new CategoriaProduto(0, "Roupas");
        CategoriaProduto cat2 = new CategoriaProduto(0, "Satapos");
        
        new CategoriaProdutoDAO().inserir(cat1);
        new CategoriaProdutoDAO().inserir(cat2);
        
        Produto prod1 = new Produto(0, "Camisa X", 1, 10, cat1);
        Produto prod2 = new Produto(0, "Bota X", 5, 20, cat2);
        
        new ProdutoDAO().inserir(prod1);
        new ProdutoDAO().inserir(prod2);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        ProdutoDAO prodDAO = new ProdutoDAO();
        Produto prod = prodDAO.selecionarPorCodigo(2);
        
        prod.setDescricao("Nova bota Vermelha");
        prodDAO.editar(prod);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdActionPerformed
        ProdutoDAO prodDAO = new ProdutoDAO();
        Produto prod = prodDAO.selecionarPorCodigo(2);
        
        prodDAO.excluir(prod);
    }//GEN-LAST:event_btnExcluirProdActionPerformed

    private void btnExcCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcCatActionPerformed
        CategoriaProdutoDAO catDAO = new CategoriaProdutoDAO();
        CategoriaProduto catProd = catDAO.selecionarPorCodigo(1);
        
        catDAO.excluir(catProd);
    }//GEN-LAST:event_btnExcCatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcCat;
    private javax.swing.JButton btnExcluirProd;
    private javax.swing.JButton btnInserir;
    // End of variables declaration//GEN-END:variables
}
